### ISSUE TITLE
PSSwagger failing to build non-azure module

### ISSUE THREAD

**Issue by rhysjtevans** [PowerShell/PSSwagger#415] opened 2018-07-09 11:22 UTC
Not able to generate a PSModule based on the OpenAPI Spec from the app
https://github.com/digitalocean/netbox

## Expected Behavior
PSSwagger should compile the OpenAPI specification to a PSModule.

## Current Behavior

It appears PSSwagger is generating the CS files based on the OpenAPI file in the Path folder but not compiling.
The Verbose output is held here - https://pastebin.com/rYfcZg0A
The Netbox json spec is hosted here - https://pastebin.com/JrzYKa7w
Interesting line [#1149]
`
 Error: ENOENT: no such file or directory, open 'C:\GeneratedModules\NetBox\0.0.1\Generated.Csharp\Models\ListOKResponseModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel.cs'
`
Also
`
No configuration found at 'file:///C:/Users/revans/'.
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.2.51->2.2.57)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.43->2.3.43)
ConvertTo-CsharpCode : AutoRest resulted in an error
At C:\Users\revans\OneDrive - Intelliflo
Limited\Documents\WindowsPowerShell\Modules\PSSwagger\0.3.0\PSSwagger.psm1:552 char:37
+ ... lyGenerationResult = ConvertTo-CsharpCode @ConvertToCsharpCode_params
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : SourceCodeGenerationError,ConvertTo-CsharpCode
`
## Steps to Reproduce (for bugs)
1. Install dependencies from Readme
2. Download the netbox OpenAPI spec
3. 
`New-PSSwaggerModule -SpecificationPath .\netbox.api.json -Path C:\GeneratedModules\ -Name NetBox  -Verbose`

## Context
We are not able to generate a Netbox API.

## Your Environment
Name                           Value
----                           -----
PSVersion                      5.1.15063.1155
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.1155
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```PowerShell

> $PSVersionTable

> PSSwagger Version 0.3.0


```

**Comment by bmanikm** [comment] 2018-07-09 18:50
Duplicate of #308.

**Comment by rhysjtevans** [comment] 2018-07-09 21:45
@bmanikm Can you explain why this is a duplicate?

**Comment by rhysjtevans** [comment] 2018-07-09 21:47
I can't find any reference to a null type in the netbox api spec.

**Comment by bmanikm** [comment] 2018-07-09 22:42
@rhysjtevans PSSwagger is not validated with the regular, non-Azure Swagger specs. #308 is for enabling the non-Azure swagger specifications, that's why I resolved this as a duplicate, please reopen this if you disagree.
From the above error, it looks like AutoRest is unable to generate the C# code for your API spec.

**Comment by rhysjtevans** [comment] 2018-07-10 07:00
In issue #308 there's a sample of it generating AWS modules successfully.
In the opening comment autorest for me does appear to generate all the C# Code.

I've scanned through a lot and from what I can see it is correct.


There are also files that match the following pattern with many "Model" words as suffixes.    
e.g.    
"Error: ENOENT: no such file or directory, open 'C:\GeneratedModules\NetBox\0.0.1\Generated.Csharp\Models\ListOKResponseModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel.cs'"

Does this fall inline with #308

**Comment by rhysjtevans** [comment] 2018-07-10 07:02
Comparing the errors I'd argue this is a different issue

**Comment by rhys-intelliflo** [comment] 2018-07-10 08:37
@bmanikm How can we re-open this issue if you agree with the above?

**Comment by aaroneg** [comment] 2018-10-29 18:28
I would also like to see some movement on this. it would be nice to have a nice auto-generated netbox module.

**Comment by deathly809** [comment] 2018-10-29 18:41
The project is not longer under development.  The AutoRest team is working on a PowerShell plugin which is going to replace this tool.  They should be previewing soon.  You can grab an unstable version over [here](https://github.com/Azure/autorest.incubator).

**Comment by aaroneg** [comment] 2018-10-29 19:01
If it's dead, someone should probably mark it as archived and point out on the main project page that it's no longer under development.

**Closed** 2019-04-16 13:30 UTC
Labels: Resolution - Duplicate
